datastax-java-driver {
  basic {
    session-name = "sports-facility-system"

    load-balancing-policy {
      local-datacenter = "dc1"
    }

    request {
      consistency = QUORUM
      serial-consistency = SERIAL
      timeout = 30 seconds
    }
  }

  advanced {
    address-translator {
      class = config.NbdAddressTranslator
    }

    connection {
      connect-timeout = 10 seconds
      init-query-timeout = 10 seconds
    }
    reconnect-on-init = true
  }
}